### ISSUE TITLE
Qfs cannot build on Ubuntu 13.0

### ISSUE THREAD

**Issue by jefferyeman** [quantcast/qfs#43]
Hi, 
    I tried to build Qfs on Ubuntu.  I did try to to run 'make' and 'cmake' but both failed during building the Kerberos service.
  
    From the error logs, it looks like the KfsKrb5.h is looking for krb5.h.  I could not find the krb5.h in repo.  any idea where I could get this?  how did you guys manage to build without krb5.h..disable kerberos support for server side auth?

Below is the error:

Linking CXX shared library libqfs_common.so
[ 15%] Built target kfsCommon-shared
[ 17%] Built target kfsrs
[ 26%] Built target kfsMeta
[ 27%] Building CXX object src/cc/krb/CMakeFiles/qfskrb.dir/KrbService.cc.o
In file included from /home/jeffery/code/qfs/src/cc/krb/KrbService.cc:28:0:
/home/sam/code/qfs/src/cc/krb/KfsKrb5.h:36:26: fatal error: krb5/krb5.h: No such file or directory
 #   include <krb5/krb5.h>
                          ^
compilation terminated.
make[3]: *** [src/cc/krb/CMakeFiles/qfskrb.dir/KrbService.cc.o] Error 1
make[2]: *** [src/cc/krb/CMakeFiles/qfskrb.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release] Error 2

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-43.
