### ISSUE TITLE
Qfs cannot build on Ubuntu 13.0

### ISSUE THREAD

**Issue by fsareshwala** [quantcast/qfs#91]
GitHub user [jefferyeman|https://github.com/jefferyeman] has created an issue on our public [GitHub Issues|https://github.com/quantcast/qfs/issues] list.

This ticket is a mirror of the first post of the public ticket on github. The purpose of this ticket is to have an owner of the public response. The owner is responsible for researching the answer and responding to the public issue in a timely manner.

https://github.com/quantcast/qfs/issues/43

*Issue Description*
{code}
Hi, 
    I tried to build Qfs on Ubuntu.  I did try to to run 'make' and 'cmake' but both failed during building the Kerberos service.
  
    From the error logs, it looks like the KfsKrb5.h is looking for krb5.h.  I could not find the krb5.h in repo.  any idea where I could get this?  how did you guys manage to build without krb5.h..disable kerberos support for server side auth?

Below is the error:

Linking CXX shared library libqfs_common.so
[ 15%] Built target kfsCommon-shared
[ 17%] Built target kfsrs
[ 26%] Built target kfsMeta
[ 27%] Building CXX object src/cc/krb/CMakeFiles/qfskrb.dir/KrbService.cc.o
In file included from /home/jeffery/code/qfs/src/cc/krb/KrbService.cc:28:0:
/home/sam/code/qfs/src/cc/krb/KfsKrb5.h:36:26: fatal error: krb5/krb5.h: No such file or directory
 #   include <krb5/krb5.h>
                          ^
compilation terminated.
make[3]: *** [src/cc/krb/CMakeFiles/qfskrb.dir/KrbService.cc.o] Error 1
make[2]: *** [src/cc/krb/CMakeFiles/qfskrb.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release] Error 2
{code}
